### ISSUE TITLE
Upgrade for Bevy 0.9

### ISSUE THREAD

**Issue by johanhelsing** [gschup/bevy_ggrs#32]
Bump Bevy to 0.9 Cargo.toml and fix porting issues

**Comment by gschup** [comment]
This seems to be non-trivial on first glance:

- GGRS sessions are added as resources and thus now need to derive bevy's Resource trait, through a feature flag in GGRS. Otherwise a wrapper struct is necessary.
- taking a snapshot of registered resources used a now no longer available API ([link](https://github.com/gschup/bevy_ggrs/blob/2363e68e22c89f271fb01e4950a5dd5a265dd1cf/src/world_snapshot.rs#L110)). In [this PR](https://github.com/bevyengine/bevy/pull/4809) resource was moved to world storage, but iterating over all resource indices is no longer possible. `world.archetypes().resource().unique_components()` gave direct access to the underlying `SparseSet<ComponentId, ResourceData>`; but in the new `world.storage.resources`, this is now private ([link](https://github.com/bevyengine/bevy/blob/0f3f628c48814c9fce49f518e5809eb500fb7a4e/crates/bevy_ecs/src/storage/resource.rs#L127))

**Comment by johanhelsing** [comment]
Is it something we could try to bring back in Bevy 0.9.1 with a different name and/or unsafe warnings?

**Comment by gschup** [comment]
I think they conciously removed this and it will not come back:

> All APIs accessing the raw data of individual resources (mutable and read-only) have been removed as these APIs allowed for unsound unsafe code. All usages of these APIs should be changed to use World::{get, insert, remove}_resource.

**Comment by Vrixyz** [comment]
It should be possible to list all resources again with `iter()` function as of bevy 0.9.1: https://github.com/bevyengine/bevy/blob/v0.9.1/crates/bevy_ecs/src/storage/resource.rs#L141.
link to bevy PR for context: https://github.com/bevyengine/bevy/pull/6592.

**Comment by gschup** [comment]
Done! Thank you for the great work @Vrixyz @johanhelsing 🎉

**Comment by gschup** [comment]
Yes, I will close this issue once a new version is published.
